import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: '{{projectName}} - Portfolio',
  description: 'A modern portfolio generated by Opusify',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="{{design}}">
      <body className="antialiased min-h-screen flex flex-col">
        
        {/* Minimalist Top Navigation */}
        <header className="sticky top-0 z-50 w-full border-b border-[var(--border)] bg-[var(--background)]/80 backdrop-blur-md animate-fade-in">
          <div className="max-w-5xl mx-auto flex h-16 items-center justify-between px-6 sm:px-12">
            
            {/* Logo / Brand Name */}
            <Link href="/" className="text-lg font-bold tracking-tighter text-[var(--foreground)]">
              {{projectName}}<span className="text-[var(--accent)]">.</span>
            </Link>
            
            {/* Navigation Links */}
            <nav className="hidden sm:flex items-center gap-6 text-sm font-medium text-[var(--muted)]">
              <Link href="/about" className="hover:text-[var(--foreground)] transition-colors">About</Link>
              <Link href="/projects" className="hover:text-[var(--foreground)] transition-colors">Projects</Link>
              <Link href="/skills" className="hover:text-[var(--foreground)] transition-colors">Skills</Link>
              <Link href="/contact" className="hover:text-[var(--foreground)] transition-colors">Contact</Link>
            </nav>
            
            {/* Mobile Menu Placeholder (Optional for later) */}
            <div className="sm:hidden text-[var(--foreground)]">
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <line x1="3" y1="12" x2="21" y2="12"></line>
                <line x1="3" y1="6" x2="21" y2="6"></line>
                <line x1="3" y1="18" x2="21" y2="18"></line>
              </svg>
            </div>

          </div>
        </header>

        {/* Main Content Area */}
        <main className="flex-1 w-full max-w-5xl mx-auto">
          {children}
        </main>

        {/* Minimal Footer */}
        <footer className="border-t border-[var(--border)] py-8 mt-12 text-center text-sm text-[var(--muted)] animate-fade-in delay-400">
          <p>© {new Date().getFullYear()} {{projectName}}. All rights reserved.</p>
        </footer>

      </body>
    </html>
  );
}